### PR TITLE
add a patch for clang 7.0

### PR DESCRIPTION
**Pull request by semnil**
I can build for the time being with The Xcode 7.0 and the OS X El Capitan 10.11.

### CODE REVIEW

**Comment by glaukommatos** [comment]
Thank you sooooooooooo much for this. You're my hero. I built the therubyracer manually with your branch and it was successful. I'd previously been banging my head against the keyboard for about ten hours.

Thank you, thank you, thank you.

:+1: :heart: :+1: :heart: :+1: :heart: :+1: :heart: :+1: :heart: :+1: :heart: 

PS: I wasn't able to have it build just by adding your branch as the source in my Gemfile, because it seems like the Gyp / v8 vendor submodules weren't getting checked out, but that might be perfectly normal. I've never had to build a Gem before, perhaps in the actual distributed versions they usually distribute an already-checked-out vendor/** directory. Because of this I ended up cloning your fork and checking out your branch before manually running rake, after which everything went by swimmingly.

THANK YOU.

**Comment by ignisf** [comment]
I wonder why the hell is this failing despite of https://github.com/cowboyd/libv8/blob/master/ext/libv8/builder.rb#L46

**Comment by semnil** [comment]
I'm exhausted.

**Comment by uberweb** [comment]
Great job! This fixes it.

**Comment by cowboyd** [comment]
@ignisf is this good to go?

**Comment by ignisf** [comment]
:+1:

**Comment by cowboyd** [comment]
Thanks @semnil!

**Comment by Aeon** [comment]
What about update for 3.16... still cannot install it on 10.11

**Comment by cowboyd** [comment]
@Aeon the [latest release for 3.16](https://rubygems.org/gems/libv8/versions/3.16.14.11) should have this patch on it. Are you sure you're using `3.16.14.11`?

**Comment by number5** [comment]
@cowboyd I can confirm this patch is *not* in `libv8-3.16.14.11`, and I have the same error in El Capitan (10.11.1)

**Comment by eugeneius** [comment]
I just ran into this as well. `v3.16.14.11` definitely doesn't contain this patch: https://github.com/cowboyd/libv8/blob/v3.16.14.11/ext/libv8/patcher.rb#L22

**Comment by aeschylus** [comment]
+1

**Comment by benwyrosdick** [comment]
It finally worked for me once I cleared out my versions of v8 installed with brew and uninstalled all my previous libv8 gems

**Comment by heaven** [comment]
```
Using libv8 3.16.14.13 (was 3.16.14.7) from git@github.com:cowboyd/libv8.git (at master@78ee254)

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /Users/heaven/.rvm/rubies/ruby-2.1.2/bin/ruby -r ./siteconf20160411-17802-ab120m.rb extconf.rb
creating Makefile
ln: build/gyp: No such file or directory
/Users/heaven/.rvm/gems/ruby-2.1.2@sharinghub/bundler/gems/libv8-78ee2548a0b1/ext/libv8/patcher.rb:51:in `block (2 levels) in patch!': failed to apply patch (RuntimeError)
	from /Users/heaven/.rvm/gems/ruby-2.1.2@sharinghub/bundler/gems/libv8-78ee2548a0b1/ext/libv8/patcher.rb:49:in `each'
	from /Users/heaven/.rvm/gems/ruby-2.1.2@sharinghub/bundler/gems/libv8-78ee2548a0b1/ext/libv8/patcher.rb:49:in `block in patch!'
	from /Users/heaven/.rvm/gems/ruby-2.1.2@sharinghub/bundler/gems/libv8-78ee2548a0b1/ext/libv8/patcher.rb:45:in `open'
	from /Users/heaven/.rvm/gems/ruby-2.1.2@sharinghub/bundler/gems/libv8-78ee2548a0b1/ext/libv8/patcher.rb:45:in `patch!'
	from /Users/heaven/.rvm/gems/ruby-2.1.2@sharinghub/bundler/gems/libv8-78ee2548a0b1/ext/libv8/builder.rb:57:in `block in build_libv8!'
	from /Users/heaven/.rvm/gems/ruby-2.1.2@sharinghub/bundler/gems/libv8-78ee2548a0b1/ext/libv8/builder.rb:52:in `chdir'
	from /Users/heaven/.rvm/gems/ruby-2.1.2@sharinghub/bundler/gems/libv8-78ee2548a0b1/ext/libv8/builder.rb:52:in `build_libv8!'
	from /Users/heaven/.rvm/gems/ruby-2.1.2@sharinghub/bundler/gems/libv8-78ee2548a0b1/ext/libv8/location.rb:24:in `install!'
	from extconf.rb:7:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /Users/heaven/.rvm/gems/ruby-2.1.2@sharinghub/bundler/gems/libv8-78ee2548a0b1 for inspection.
Results logged to /Users/heaven/.rvm/gems/ruby-2.1.2@sharinghub/bundler/gems/extensions/x86_64-darwin-15/2.1.0/libv8-78ee2548a0b1/gem_make.out
```

**Pull request merged**
