### PR TITLE
Upgrade to v8 6.9

### PR DESCRIPTION
**Pull request by rafaelfranca**
This will add support to MacOS 10.14 Mojave.

I could build and install locally, but not sure what else I should change.

cc @ignisf

### CODE REVIEW

**Comment by ignisf** [comment]
Hello @rafaelfranca, thank you for the PR!

Do you happen to know which specific commit adds support for 10.14? I don't feel comfortable releasing a V8 version that is not even in the canary channel of Chromium (see https://omahaproxy.appspot.com/). Maybe we could backport the fixes instead?

**Comment by ignisf** [comment]
In the meantime, I've repackaged the darwing-16 binary for darwin-18, could you please test it?

https://github.com/cowboyd/libv8/releases/download/v6.7.288.46.1/libv8-6.7.288.46.1-x86_64-darwin-18.gem

https://github.com/cowboyd/libv8/releases/download/v6.7.288.46.1/libv8-6.7.288.46.1-universal-darwin-18.gem

**Comment by rafaelfranca** [comment]
The commit is this one. It is a change in the build tool and I don't know how to track where v8 changed the code to use the new version of the build tool https://chromium.googlesource.com/chromium/src/build/+/4287a0d364541583a50cc91465330251460d489a%5E%21/#F1.

I tested the x86_64 binary and it worked, are you planning to release to rubygems?

**Comment by ignisf** [comment]
@rafaelfranca, well now that you've confirmed it's working -- yes, I'll push it to rubygems.

**Comment by rafaelfranca** [comment]
Thanks! Should I close this PR?

**Comment by ignisf** [comment]
I'll close it for now. Hopefully the binary will do until upstream support hits a stable version.

**Pull request closed without merging**
