### PR TITLE
Fix compatibility with psych 4.0

### LINKED ISSUE #322: psych 4.x breaks libv8 `.location.yml` deserialisation during extension building
Experiencing similar issue to https://github.com/rubyjs/mini_racer/issues/208 in that the attempt to load the `.location.yml`.  Believe the introduced fix https://github.com/rubyjs/libv8-node/commit/6bbb084522a0497b5ff8e810df300098a5e45ad9 should be the same to update in this library.  
https://github.com/rubyjs/libv8/blob/v8.4.255.0/ext/libv8/location.rb#L16

I validated that the file that was attempting to load noted
```
/Users/gh7199/.rvm/gems/ruby-2.6.6@embedded_content_engine/gems/libv8-3.16.14.19/ext/libv8/.location.yml
```

```
Installing therubyracer 0.12.3 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/gh7199/.rvm/gems/ruby-2.6.6@embedded_content_engine/gems/therubyracer-0.12.3/ext/v8
/Users/gh7199/.rvm/rubies/ruby-2.6.6/bin/ruby -I /Users/gh7199/.rvm/rubies/ruby-2.6.6/lib/ruby/site_ruby/2.6.0 -r ./siteconf20220104-25212-1w22w49.rb extconf.rb --with-v8-dir\=/usr/local/opt/v8@3.15
checking for -lpthread... yes
checking for -lobjc... yes
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/gh7199/.rvm/rubies/ruby-2.6.6/bin/$(RUBY_BASE_NAME)
	--with-pthreadlib
	--without-pthreadlib
	--with-objclib
	--without-objclib
	--enable-debug
	--disable-debug
/Users/gh7199/.rvm/gems/ruby-2.6.6@embedded_content_engine/gems/psych-4.0.3/lib/psych/class_loader.rb:99:in `find': Tried to load unspecified class: Libv8::Location::System (Psych::DisallowedClass)
	from /Users/gh7199/.rvm/gems/ruby-2.6.6@embedded_content_engine/gems/psych-4.0.3/lib/psych/class_loader.rb:28:in `load'
	from /Users/gh7199/.rvm/gems/ruby-2.6.6@embedded_content_engine/gems/psych-4.0.3/lib/psych/visitors/to_ruby.rb:424:in `resolve_class'
	from /Users/gh7199/.rvm/gems/ruby-2.6.6@embedded_content_engine/gems/psych-4.0.3/lib/psych/visitors/to_ruby.rb:213:in `visit_Psych_Nodes_Mapping'
	from /Users/gh7199/.rvm/gems/ruby-2.6.6@embedded_content_engine/gems/psych-4.0.3/lib/psych/visitors/visitor.rb:30:in `visit'
	from /Users/gh7199/.rvm/gems/ruby-2.6.6@embedded_content_engine/gems/psych-4.0.3/lib/psych/visitors/visitor.rb:6:in `accept'
	from /Users/gh7199/.rvm/gems/ruby-2.6.6@embedded_content_engine/gems/psych-4.0.3/lib/psych/visitors/to_ruby.rb:35:in `accept'
	from /Users/gh7199/.rvm/gems/ruby-2.6.6@embedded_content_engine/gems/psych-4.0.3/lib/psych/visitors/to_ruby.rb:318:in `visit_Psych_Nodes_Document'
	from /Users/gh7199/.rvm/gems/ruby-2.6.6@embedded_content_engine/gems/psych-4.0.3/lib/psych/visitors/visitor.rb:30:in `visit'
	from /Users/gh7199/.rvm/gems/ruby-2.6.6@embedded_content_engine/gems/psych-4.0.3/lib/psych/visitors/visitor.rb:6:in `accept'
	from /Users/gh7199/.rvm/gems/ruby-2.6.6@embedded_content_engine/gems/psych-4.0.3/lib/psych/visitors/to_ruby.rb:35:in `accept'
	from /Users/gh7199/.rvm/gems/ruby-2.6.6@embedded_content_engine/gems/psych-4.0.3/lib/psych.rb:335:in `safe_load'
	from /Users/gh7199/.rvm/gems/ruby-2.6.6@embedded_content_engine/gems/psych-4.0.3/lib/psych.rb:370:in `load'
	from /Users/gh7199/.rvm/gems/ruby-2.6.6@embedded_content_engine/gems/libv8-3.16.14.19/ext/libv8/location.rb:17:in `block in load!'
	from /Users/gh7199/.rvm/gems/ruby-2.6.6@embedded_content_engine/gems/libv8-3.16.14.19/ext/libv8/location.rb:15:in `open'
	from /Users/gh7199/.rvm/gems/ruby-2.6.6@embedded_content_engine/gems/libv8-3.16.14.19/ext/libv8/location.rb:15:in `load!'
	from /Users/gh7199/.rvm/gems/ruby-2.6.6@embedded_content_engine/gems/libv8-3.16.14.19/lib/libv8.rb:6:in `configure_makefile'
	from extconf.rb:32:in `<main>'
```

### PR DESCRIPTION
**Pull request by poloka**
Add psych 4.0 compatibility fix that fixes #322 .

### CODE REVIEW

**Comment by poloka** [comment]
@SamSaffron any support for this change?  Would like patches pushed back all the way to the 3.x pipeline.

**Comment by SamSaffron** [comment]
This looks fine to me... @lloeki I am going to merge this... feel free to do backport prs as well.

**Comment by lloeki** [comment]
@poloka may I ask what is the dependency that you depend on that makes you depend on libv8?

IOW what is precluding a move to mini_racer?

**Comment by poloka** [comment]
@mitorez you are correct. We have an internal dependency that we do not have control of right now that depends on therubyracer that pulls in the 3.x series of libv8.

**Comment by SamSaffron** [comment]
therubyracer is incredibly high risk at this point in time... there are so many unpatched CVEs in ancient versions of v8...

**Comment by poloka** [comment]
Don't disagree.  We need to get off it.

**Comment by poloka** [comment]
@SamSaffron @lloeki is it possible to get this released in a patch back to the 3.x?  If wiki instructions were updated on how to build this locally, test, and then how to release I'd be open to tagging the releases.  I attempted to pull the latest and build and I must be missing something because I cannot get it working locally on my M1 mac.  Looks like travis CI is no longer building this project.

**Comment by lloeki** [comment]
I'll hack something.

**Comment by mitorez** [comment]
> I'll hack something.

Thank you very much, @lloeki! If the version number could be something like `3.16.14.xx` (e.g.; `3.16.14.20`) that would be great, since that would allow the latest version of `therubyracer` to pick it up without it being rebuilt as well.

**Comment by lloeki** [comment]
> If wiki instructions were updated on how to build this locally, test, and then how to release

TBH it's pointless, not the least because this libv8 version is extremely old and insecure.

> I cannot get it working locally on my M1 Mac

You're not missing anything, this version of libv8 is outstandingly outdated and has issues with recent compiler and environments, even on Intel. It just does not support arm64-darwin; even if it produces a build it is not amenable to reliably run under Rosetta 2. Attempting to reliably have it do a consistent Intel build on M1 through Rosetta is an exercise in frustration.

> Looks like travis CI is no longer building this project.

Cue the above: running unreliable jobs on CI achieves very little in comparison to the effort of moving CIs, even more so for an outdated project.

> it's a deprecated internal dependency that depends on therubyracer that we cannot migrate off of yet because of time constraints.

I can understand the realities of development - hence why I'll hack something - and I certainly don't want to sound judgemental. That said, relying on such an old version of v8 and conversely on therubyracer, which cannot be upgraded to later v8 versions without extreme ~prejudice~ amounts of work, is a serious liability and a migration should have been considered with increasingly high priority as time has passed.

From CI to up-to-date v8, mini_racer's raison d'être is to tackle these issues, which is a hard-enough task in and of itself, so within the bounds of the time we can allocate to rubyjs that's where our focus is.

@SamSaffron WDYT about putting out a notice on the README of libv8 and therubyracer highlighting the status of both, with a recommendation to move to mini_racer+libv8-node?

**Comment by mitorez** [comment]
@lloeki Completely agree with everything you stated above^

_Poor planning on our part does not necessitate an emergency on yours._

If you're able to hack something together, it would be very much appreciated. If you're not able to for whatever reason, that's totally understandable. I understand these projects are EOL, even if that's not explicitly stated - so any help we receive from you, we know it's above and beyond.

We are getting off our deprecated internal dependency as well as these, but unfortunately it's a large effort and that time frame doesn't lineup with the new internal push to update to Ruby 3.2, which is the only reason we were looking at this patch/hack. TMI...

Thank you again for your time looking into this issue.

**Comment by lloeki** [comment]
For 3.16.14.19:

```
platforms=(
  '-arm-linux'
  '-x86-linux'
  '-amd64-freebsd-10'
  '-amd64-freebsd-11'
  '-x86_64-linux'
  '-armv7l-linux'
  '-x86_64-darwin-18'
  '-universal-darwin-17'
  ''
)
```

```
for platform in "${platforms[@]}"; do
    url="https://rubygems.org/downloads/libv8-3.16.14.19${platform}.gem"
    curl -O "${url}"
done
```

```
for platform in "${platforms[@]}"; do
    unpack_gem "libv8-3.16.14.19${platform}.gem"
done
```

```
cat > patch.sh <<'EOF' && chmod +x patch.sh
#!/usr/bin/env bash

set -e
set -u
set -o pipefail

test -f 3cb539da6b3d850dc1ec15e168a744d18ff3d35a.patch || curl -O https://github.com/rubyjs/libv8/commit/3cb539da6b3d850dc1ec15e168a744d18ff3d35a.patch

dir="$1"

cd "${dir}/data"
patch -p1 < ../../3cb539da6b3d850dc1ec15e168a744d18ff3d35a.patch
cd ..

perl -p -i -e 's/platform: (.+)-darwin-\d+/platform: \1-darwin/' metadata
perl -p -i -e 's/version: 3\.16\.14\.19/version: 3.16.14.19.1/' metadata
perl -p -i -e 's/VERSION = "3\.16\.14\.19"/VERSION = "3.16.14.19.1"/' data/lib/libv8/version.rb
EOF
```

```
for platform in "${platforms[@]}"; do
    ./patch.sh "libv8-3.16.14.19${platform}"
done
```

```
for platform in "${platforms[@]}"; do
    cat "libv8-3.16.14.19${platform}"/metadata | grep platform:
    cat "libv8-3.16.14.19${platform}"/metadata | grep '^  version:'
    cat "libv8-3.16.14.19${platform}"/data/lib/libv8/version.rb | grep VERSION
    cat "libv8-3.16.14.19${platform}"/data/ext/libv8/location.rb | grep safe_load
done
```

```
for platform in "${platforms[@]}"; do
    new_platform="$(cat "libv8-3.16.14.19${platform}"/metadata | perl -ne '/platform: (.*)$/ and print "$1\n"')"
    if [[ "${new_platform}" != "ruby" && "libv8-3.16.14.19${platform}" != "libv8-3.16.14.19-${new_platform}" ]]; then
        echo "${platform#-} -> ${new_platform}"
        mv "libv8-3.16.14.19${platform}" "libv8-3.16.14.19-${new_platform}"

        rm "libv8-3.16.14.19${platform}.gem"
        pack_gem "libv8-3.16.14.19-${new_platform}"
    else
        rm "libv8-3.16.14.19${platform}.gem"
        pack_gem "libv8-3.16.14.19${platform}"
    fi
done
```

**Pull request merged**
