### PR TITLE
Use "github" instead of "git" for Bundler.

### PR DESCRIPTION
**Pull request by envygeeks**

### CODE REVIEW

**Comment by michaelglass** [comment]
kind of pedantic, why?

**Comment by ignisf** [comment]
@envygeeks, thank you for the PR! If I'm not mistaken, [bundler 1.8.0] added the `github` option. Could you add back the 'old' way of specifying a git gem with a note saying something like 'If you are using bundler pre-1.8.0 use this' or something like that. 

[bundler 1.8.0]: https://github.com/bundler/bundler/blob/master/CHANGELOG.md#180-2015-02-10

**Comment by envygeeks** [comment]
@ignisf it's been around since v1.1.0 (http://bundler.io/v1.1/git.html) but I will add back in the classic Git example because it's probably good to give an example of that too.  The ticket you linked to is for another type of Github syntax: https://github.com/bundler/bundler/issues/3379

**Comment by ignisf** [comment]
ah

**Pull request merged**
