### PR TITLE
Added support for windows platforms using mingw.

### PR DESCRIPTION
**Pull request by jarredholman**
Adds windows support using mingw compiler that comes with rubyinstaller's devkit.

Also requires Python27 (official windows build) and msysgit.

To build, open cmd.exe shell
> set PATH=%PATH%;C:\Python27;C:\Program Files (x86)\Git\bin
> c:\ruby-devkit-mingw64\devkitvars.bat
> bundle install
> bundle exec rake compile

mingw-generate-makefiles.sh script is a modified version from v8 source (modification just adds x64 target).

### CODE REVIEW

**Comment by cowboyd** [comment]
Are there any hosted CI solutions that support windows builds?

**Comment by ignisf** [comment]
I don't believe I've heard of any

**Comment by jarredholman** [comment]
Could try http://www.appveyor.com/ ?

**Comment by cowboyd** [comment]
Looks promising. I've set up a project there to build libv8 https://ci.appveyor.com/project/cowboyd/libv8

but it looks like it needs an `appveyor.yml` to get working. It should build pull requests, if you have any experience with appveyor, it would be awesome if you could submit one to get it working :)

**Comment by jarredholman** [comment]
I haven't used it before but it doesn't look too hard so I'll have a go at it.

**Comment by jarredholman** [comment]
Added a first attempt. I only really tested that it worked for ruby21-x64 but I've enabled all the ruby versions to see what happens.

There is one slight problem. It rebuilds v8_base again for the "host" after doing it for the "target" so that it can run "tools_gyp_v8_gyp_js2c_host_js2c".
This is making the build get dangerously close to the 30 minute time limit.

I looked at the Travis CI log and it seems like the linux build doesn't do that so I'm not sure why this would be different.

**Comment by jarredholman** [comment]
Seems like the time was not as bad as I thought...

**Comment by cowboyd** [comment]
Whoa, that was easy. If you're ok with this @ignisf, let's merge it.

**Pull request merged**
