### PR TITLE
[WIP] Upgrade to upstream v8 6.7

### LINKED ISSUE #228: GYP has been deprecated in favor of GN
https://github.com/v8/v8/wiki/Building%20with%20Gyp

https://github.com/v8/v8/wiki/Building%20with%20GN
- [x] Find a way to produce a standalone archive instead of a thin one. Keywords in the ninja build files: `standalone_static_library`, `alink` and `alink_thin`.
- [x] Find a way to produce an `-fPIC` library (it could be possible to specify additional flags via a ninja build flag)
- [x] Skip building the test suite (it could be possible to give ninja a specific target to build)
- [ ] Use the system toolchain instead of the built-in ones (see ninja argument)
- [ ] Use the system binutils
- [ ] Use the system ld

### LINKED ISSUE #255: V8 6.3 exposes its users to the Meltdown and Spectre attacks if used for executing untrusted code
As far as I understand, the following conditions need to be met:
1. You have to be using V8 to run untrusted code.
2. You have to be running V8 on an unpatched OS.

Mitigations have been merged in 6.4 beta, see:

* https://github.com/v8/v8/commit/a060a4fc565aa40fcb3acb6b075936b78b38fc10
* https://chromium-review.googlesource.com/c/v8/v8/+/848921
* https://sites.google.com/a/chromium.org/dev/Home/chromium-security/ssca

* https://googleprojectzero.blogspot.bg/2018/01/reading-privileged-memory-with-side.html
* https://spectreattack.com/
* https://meltdownattack.com/

### PR DESCRIPTION
**Pull request by ignisf**
- [x] Update build automation
- [x] Check FreeBSD support (none until https://github.com/cowboyd/libv8/issues/253 is fixed)
- [x] Check Alpine support (none until https://github.com/cowboyd/libv8/issues/259 is fixed)
- [x] Check ARM support
- [ ] Automate creation of debug binary

Fixes #255 
Fixes #228
Fixes https://github.com/discourse/mini_racer/issues/85

### CODE REVIEW

**Comment by SamSaffron** [comment]
@ignisf any chance for a release this week, super keep to bump mini_racer due to segfault etc...

**Comment by ignisf** [comment]
@SamSaffron, I've been trying to get the library to compile for ARM, and have not been able to. If we release now, we're losing support for ARM, FreeBSD and Alpine Linux...

Now, I am fine with that, considering this PR nukes all the functionality that made it possible to compile for those platforms with GYP, however maybe mini_racer should have a version with the segfault-related fixes that depends on the older more portable V8 version?

**Comment by SamSaffron** [comment]
OK, no problem ❤️ ... 0.2.0 is now out and it is cross compatible with 6.3 and up 

So this gives us some time to get ARM support (though for Discourse I am going to push the libv8 dep explicitly to 6.7)

**Comment by ignisf** [comment]
yes, awesome!

**Comment by ignisf** [comment]
it's live :tada:

**Comment by SamSaffron** [comment]
Yay!!!

Going to upgrade Discourse on Monday!

**Pull request merged**
