### PR TITLE
Upgrade to v8 4.5

### PR DESCRIPTION
**Pull request by cowboyd**
This upgrades to the 4.5 build process which uses the Chromium depot tools.

This completely removes the v8 source as a submodule and instead uses `fetch` and `gclient sync` to configure all build dependencies.

### CODE REVIEW

**Comment by cowboyd** [comment]
Something is going awry with the python scripts in `vendor/depot_tools` they work on my machine and on my linux vms, but not on Travis.

**Comment by ignisf** [comment]
Will take a look

**Comment by cowboyd** [comment]
As far as I can tell, the compilation is completing, on Travis, but the expected archives are not present.... strange

**Comment by ignisf** [comment]
Hmm, it seems that instead of a single snapshot archive, we now have

```
-rw-r--r-- 1 ignisf ignisf 1591270  5 юли 17,40 libv8_base.a
-rw-r--r-- 1 ignisf ignisf    2746  5 юли 17,40 libv8_external_snapshot.a
-rw-r--r-- 1 ignisf ignisf   12006  5 юли 17,40 libv8_libbase.a
-rw-r--r-- 1 ignisf ignisf    4036  5 юли 17,40 libv8_libplatform.a
-rw-r--r-- 1 ignisf ignisf    2460  5 юли 17,40 libv8_nosnapshot.a
```

Which of these do we need?

**Comment by cowboyd** [comment]
As you might have guessed, I'm using this branch to try and press forward on the work that @stormbreakerbg started here https://github.com/stormbreakerbg/therubyracer/tree/v8-update

We need `libv8_base.a`, `libv8_libbase.a`, `libv8_libplatform.a`, `libv8_snapshot.a`

Although it looks like it names `libv8_snapshot.a` `libv8_external_snapshot.a` on linux? That's strange.

**Comment by cowboyd** [comment]
It would also explain why the installation verification is failing on Travis.

**Comment by cowboyd** [comment]
The `lib_external_snapshot.a` is not present for me.
```
❯❯❯ ls -l vendor/v8/out/x64.release
total 1195408
-rwxr-xr-x   1 cowboyd  staff   12790708 Jul  3 14:59 d8
-rwxr-xr-x   1 cowboyd  staff   12612492 Jul  3 14:59 hello-world
-rw-r--r--   1 cowboyd  staff  531505240 Jul  3 14:59 libv8_base.a
-rw-r--r--   1 cowboyd  staff     562224 Jul  3 14:59 libv8_libbase.a
-rw-r--r--   1 cowboyd  staff     404080 Jul  3 14:59 libv8_libplatform.a
-rw-r--r--   1 cowboyd  staff    1830536 Jul  3 14:59 libv8_nosnapshot.a
-rw-r--r--   1 cowboyd  staff    2376536 Jul  3 14:59 libv8_snapshot.a
-rwxr-xr-x   1 cowboyd  staff   12067044 Jul  3 14:59 mksnapshot
drwxr-xr-x   3 cowboyd  staff        102 Jul  3 14:59 obj
drwxr-xr-x  16 cowboyd  staff        544 Jul  3 14:59 obj.target
-rwxr-xr-x   1 cowboyd  staff   12618012 Jul  3 14:59 parser-shell
-rwxr-xr-x   1 cowboyd  staff   12634060 Jul  3 14:59 process
-rwxr-xr-x   1 cowboyd  staff   12622948 Jul  3 14:59 shell
```

**Comment by ignisf** [comment]
https://github.com/v8/v8-git-mirror/commit/61509aaea57b767dcdc47e2b74842c3c462457ca

**Comment by ignisf** [comment]
Ah,

`Makefile`
```
# snapshot=off
ifeq ($(snapshot), off)
  GYPFLAGS += -Dv8_use_snapshot='false'
endif
ifeq ($(snapshot), external)
  GYPFLAGS += -Dv8_use_external_startup_data=1
endif
```

**Comment by ignisf** [comment]
What concerns me is this snippet of the `standalone.gypi` file:

```
      ['OS=="linux"', {
        # Gradually roll out v8_use_external_startup_data.
        # Should eventually be default enabled on all platforms.
        'v8_use_external_startup_data%': 1,
```

**Comment by cowboyd** [comment]
Yeah, I wonder what kind of requirements that puts onto the embedder. It might just be that the startup time is not nearly as fast, although I don't think that they'll deprecate the builtin startup data, so it should be safe to set `snapshot=on` in our make flags

**Comment by ignisf** [comment]
Setting it to `on` has no effect on my side. Possibly due to aforementioned snippet.

**Comment by cowboyd** [comment]
blech, ok, sounds like we'll have to start loading the startup data by hand. Let's just assume that then on all platforms, and I'll make whatever adjustments I have to, to make it work.

**Comment by ignisf** [comment]
If you deem it unfeasible, we can set `GYP_DEFINES="v8_use_external_startup_data=0"` for now

**Comment by cowboyd** [comment]
@jarredholman As part of upgrading to v8 version 4.5.x, we lost support for building Windows. Is there any way you can  look at this branch to see if we can get Windows working again? I've tried my limited Windows/Appveyor skills, but have to admit that I haven't been very effective.

**Comment by ignisf** [comment]
@cowboyd, can you grant me rights to the project in appveyor?

**Comment by cowboyd** [comment]
@ignisf done! The permissions on appveyor are a bit fiddly and confusing. Let me know if that doesn't let you do what you want.

**Comment by jarredholman** [comment]
I can have a look although I don't think it will be as simple as last time.

**Comment by cowboyd** [comment]
Should we drop the windows support for this version, until somebody with expertise can come along and fix it?

**Comment by ignisf** [comment]
yes, lets.

**Comment by cowboyd** [comment]
Sheesh. I'm the guy who fights always fights with the v8 build and ends up on the floor unconsious. 

There is a `standalone_static_library` option referenced in gyp/generators/make.py, that can be turned on somehow. I thought I'd figured it out, but apparently not. If we can somehow turn that on, then we can actually build linux binaries.

**Comment by ignisf** [comment]
It was a tough one...
```
-rw-r--r--  1 ignisf ignisf  10M 13 юли 15,29 libv8-4.5.95.5-x86_64-linux.gem
```

**Comment by cowboyd** [comment]
You magnificent bastard.

you got me you beautiful bastard _c79b658e8e1f7e21575aa9d9e7533b56

**Comment by cowboyd** [comment]
I noticed with this change, that it puts the archives in the main product dir, just like on darwin, and freebsd, so no need to [check in two places][1] for the object files, which was a hack to begin with.

I think we're getting damn close to master here.

[1]: https://github.com/cowboyd/libv8/blob/master/ext/libv8/paths.rb#L25-L27

**Comment by cowboyd** [comment]
So after the remaining 2 PR's is there any work left to do before merging to master?

**Comment by ignisf** [comment]
What I think would be nice is to package only the needed sources in the source distribution of the gem and not execute depot tools when it's installed. IIRC the patcher needed to be executed upon installation because there are environment-specific patches that need to be applied. The source however is the same for everybody.

This does not stop us from merging into master.

**Comment by ignisf** [comment]
Disregard that.. This would break using from Github

**Comment by cowboyd** [comment]
Believe it or not, I actually tried that at first, but 

1. All the crap depot tools pooped into vendor/v8 was something like 125M
1. the build lost its mind when it found that `vendor/v8` was not a git repot.

**Comment by mintrigue** [comment]
Is this upgrade dead?

**Comment by jarredholman** [comment]
On the windows side of things, getting the build working is a nightmare.

**Pull request merged**
