### PR TITLE
use container based builds on travis

### PR DESCRIPTION
**Pull request by cowboyd**
http://docs.travis-ci.com/user/migrating-from-legacy

### CODE REVIEW

**Comment by cowboyd** [comment]
Supposedly, these get more resources, but it actually seemed slower. Of course, it is all highly dependent on time of day

**Comment by ignisf** [comment]
They do start in seconds. I restarted a job to make sure.

**Comment by cowboyd** [comment]
Alrightee, your call then.  :vertical_traffic_light:

**Comment by cowboyd** [comment]
As a side note, we'd speed things up greatly if we could somehow speed up the checkout of the v8 source. Cloning that entire repo is brutal, but I couldn't find any way to do a shallow clone of a specific branch/tag with the `fetch` depot tool.

**Comment by ignisf** [comment]
May I just express my opinion of how immensely not invented here the `depot_tools` are?

**Comment by ignisf** [comment]
https://code.google.com/p/chromium/issues/detail?id=228996 but before you get your hopes up, this does not work for our case -- this checks out always the latest HEAD version and one cannot check out the version we need without defeating the purpose of the shallow clone OR the use of `depot_tools`

**Comment by cowboyd** [comment]
Even that would be an understatement. It's amazing that no one, at any point was like:

 "whoa!..... whoa! guys! .... what are we.... where are we exactly going here with this?"

As someone who dislikes git submodules, I don't see what problem depot_tools solves that submodules don't. Also, they have the advantage of being zero lines of code, as opposed to the hairball swamp of bash and python in which we find ourselves..

Also, I find the book-length goop of python configuration files otherwise known as a GYP configuration an abomination.

**Comment by ignisf** [comment]
So, the only alternative of the '`fetch` on every build' routine I've managed to devise is the following strategy:

1. Remove the `.gclient` and `.gclient_entries` files from `.gitignore`.
3. Add a submodule for `vendor/v8` (yes, again :cry:) and check out the version that we need.

2. Move the `fetch` invocation to a `rake upstream:update` task or something similar (this task will delete the `.gclient` `.gclient_entries` and `v8`, fetch the latest `v8` and do a `git add` for the updated files and submodule.

4. Run just `gclient sync --shallow --no-history` in `vendor/v8` on each build.

**Comment by cowboyd** [comment]
I'd love to see that working, and I'm totally cool giving it a try, but we should do that as a separate, experiment.

**Comment by ignisf** [comment]
:+1:

**Pull request merged**
